"""BrandForge configuration and linguistic building blocks."""

from __future__ import annotations

from pathlib import Path
from typing import Final

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict

ROOT_DIR: Final[Path] = Path(__file__).resolve().parent.parent
OUTPUT_DIR: Final[Path] = ROOT_DIR / "output"
REPORTS_DIR: Final[Path] = OUTPUT_DIR / "reports"
LOGOS_DIR: Final[Path] = OUTPUT_DIR / "logos"

# ── Default linguistic roots & suffixes ──────────────────────────────────────

DEFAULT_PREFIXES: Final[tuple[str, ...]] = (
    "mer",
    "syn",
    "ora",
    "ly",
    "zen",
    "ver",
    "lum",
    "nex",
    "vio",
    "tri",
    "xel",
    "nor",
    "vel",
    "kor",
    "ava",
    "eli",
    "nov",
    "aero",
    "bolt",
    "cryo",
    "flux",
    "glow",
    "helix",
    "ion",
    "jade",
    "kite",
    "lex",
    "mira",
    "nova",
    "orbit",
    "pulse",
    "quar",
    "rift",
    "sol",
    "tess",
    "ultra",
    "vex",
    "wave",
    "axon",
    "byte",
    "core",
    "drift",
    "echo",
    "forge",
    "grid",
    "hive",
    "iris",
    "jolt",
    "knot",
    "loom",
    "mint",
    "node",
    "onyx",
    "prism",
    "quark",
    "ray",
    "spark",
    "tide",
    "unit",
    "volt",
    "warp",
)

DEFAULT_SUFFIXES: Final[tuple[str, ...]] = (
    "iq",
    "ix",
    "io",
    "ora",
    "exa",
    "ivo",
    "ium",
    "ent",
    "ixa",
    "eo",
    "via",
    "on",
    "is",
    "us",
    "ify",
    "ifya",
    "ara",
    "era",
    "ica",
    "ly",
    "lab",
    "hub",
    "soft",
    "ware",
    "base",
    "flow",
    "link",
    "mint",
    "nest",
    "path",
    "port",
    "rise",
    "ship",
    "stack",
    "sync",
    "tech",
    "verse",
    "wise",
    "works",
    "yard",
    "zone",
    "ably",
    "ance",
    "ency",
)

# Category-tuned roots (module 2)
CATEGORY_PREFIXES: Final[dict[str, tuple[str, ...]]] = {
    "ai": (
        "neo",
        "syn",
        "neur",
        "cogn",
        "mind",
        "intel",
        "axiom",
        "prompt",
        "agent",
        "neural",
        "lexi",
        "orbi",
        "quanta",
        "tensor",
        "voxel",
        "nova",
        "lumen",
        "synapse",
        "cortex",
        "algo",
        "byte",
        "data",
        "deep",
        "gen",
        "infer",
        "logic",
        "model",
        "opti",
        "pred",
        "smart",
        "think",
        "vision",
        "auto",
        "cognito",
        "lex",
        "mira",
        "ora",
        "zen",
    ),
    "ecommerce": (
        "cart",
        "shop",
        "buy",
        "vend",
        "mart",
        "baza",
        "trade",
        "deal",
        "swift",
        "parcel",
        "box",
        "crate",
        "ship",
        "store",
        "rack",
        "shelf",
        "tag",
        "price",
        "offer",
        "glow",
        "luxe",
        "mira",
        "nova",
        "ora",
        "pulse",
        "rise",
        "spark",
        "tide",
        "velvet",
        "zen",
    ),
    "healthcare": (
        "vita",
        "cura",
        "medi",
        "heal",
        "pulse",
        "care",
        "bio",
        "gene",
        "soma",
        "thera",
        "clinic",
        "pharma",
        "sanus",
        "aegis",
        "lumen",
        "ora",
        "vitae",
        "well",
        "nura",
        "remedy",
        "flora",
        "helix",
        "iris",
        "nova",
        "solace",
        "zen",
    ),
    "finance": (
        "fin",
        "cred",
        "ledger",
        "vault",
        "coin",
        "pay",
        "capital",
        "asset",
        "fund",
        "wealth",
        "treasury",
        "mint",
        "folio",
        "equity",
        "yield",
        "apex",
        "forge",
        "gold",
        "lumen",
        "nova",
        "ora",
        "pulse",
        "sol",
        "trust",
        "vex",
        "zen",
    ),
    "cybersecurity": (
        "cipher",
        "vault",
        "shield",
        "fort",
        "sentinel",
        "guard",
        "lock",
        "secure",
        "aegis",
        "bastion",
        "crypt",
        "firewall",
        "hash",
        "key",
        "nexus",
        "onyx",
        "raven",
        "spectre",
        "threat",
        "ward",
        "zero",
        "bolt",
        "forge",
        "grid",
        "nova",
        "ora",
        "pulse",
        "rift",
        "sol",
        "vex",
    ),
    "education": (
        "learn",
        "edu",
        "tutor",
        "academy",
        "skill",
        "course",
        "mentor",
        "spark",
        "bright",
        "quest",
        "study",
        "class",
        "lesson",
        "path",
        "rise",
        "wise",
        "lumen",
        "mira",
        "nova",
        "ora",
        "pulse",
        "sol",
        "zen",
        "forge",
        "grid",
        "hive",
        "iris",
        "lex",
        "loom",
    ),
    "cloud": (
        "cloud",
        "sky",
        "nimbus",
        "strata",
        "orbit",
        "stack",
        "scale",
        "edge",
        "node",
        "cluster",
        "deploy",
        "infra",
        "kube",
        "mesh",
        "pipe",
        "relay",
        "stream",
        "aero",
        "bolt",
        "core",
        "drift",
        "echo",
        "flux",
        "forge",
        "grid",
        "hive",
        "ion",
        "nova",
        "ora",
        "pulse",
        "rift",
        "sol",
        "volt",
        "warp",
        "zen",
    ),
}

CATEGORY_SUFFIXES: Final[dict[str, tuple[str, ...]]] = {
    "ai": (
        "ai",
        "iq",
        "ix",
        "io",
        "ora",
        "ivo",
        "ium",
        "ent",
        "ixa",
        "ly",
        "lab",
        "mind",
        "bot",
        "gpt",
        "llm",
        "sense",
        "think",
        "wise",
        "forge",
        "hub",
        "ify",
        "via",
        "on",
        "is",
        "us",
        "exa",
        "eo",
    ),
    "ecommerce": (
        "ly",
        "ify",
        "shop",
        "cart",
        "mart",
        "hub",
        "box",
        "bay",
        "co",
        "io",
        "ora",
        "ivo",
        "via",
        "on",
        "is",
        "us",
        "ent",
        "ixa",
        "rise",
        "flow",
        "link",
        "nest",
        "port",
        "zone",
    ),
    "healthcare": (
        "care",
        "health",
        "med",
        "vita",
        "ora",
        "ivo",
        "ium",
        "ent",
        "ixa",
        "ly",
        "lab",
        "via",
        "on",
        "is",
        "us",
        "eo",
        "iq",
        "ix",
        "io",
        "well",
        "life",
        "pulse",
    ),
    "finance": (
        "pay",
        "fin",
        "cap",
        "ly",
        "ify",
        "ora",
        "ivo",
        "ium",
        "ent",
        "ixa",
        "io",
        "via",
        "on",
        "is",
        "us",
        "mint",
        "vault",
        "folio",
        "wise",
        "hub",
        "lab",
        "flow",
        "link",
    ),
    "cybersecurity": (
        "sec",
        "guard",
        "shield",
        "vault",
        "lock",
        "ora",
        "ivo",
        "ium",
        "ent",
        "ixa",
        "io",
        "via",
        "on",
        "is",
        "us",
        "iq",
        "ix",
        "forge",
        "hub",
        "lab",
        "wire",
        "net",
        "ops",
    ),
    "education": (
        "edu",
        "learn",
        "lab",
        "hub",
        "ly",
        "ify",
        "ora",
        "ivo",
        "ium",
        "ent",
        "ixa",
        "io",
        "via",
        "on",
        "is",
        "us",
        "wise",
        "path",
        "quest",
        "rise",
        "spark",
        "class",
    ),
    "cloud": (
        "cloud",
        "ops",
        "stack",
        "scale",
        "ora",
        "ivo",
        "ium",
        "ent",
        "ixa",
        "io",
        "via",
        "on",
        "is",
        "us",
        "iq",
        "ix",
        "hub",
        "lab",
        "forge",
        "grid",
        "mesh",
        "pipe",
        "sync",
        "ware",
        "zone",
    ),
}

CATEGORY_ALIASES: Final[dict[str, str]] = {
    "ai": "ai",
    "artificial-intelligence": "ai",
    "ml": "ai",
    "ecommerce": "ecommerce",
    "e-commerce": "ecommerce",
    "commerce": "ecommerce",
    "shop": "ecommerce",
    "healthcare": "healthcare",
    "health": "healthcare",
    "medical": "healthcare",
    "med": "healthcare",
    "finance": "finance",
    "fintech": "finance",
    "fin": "finance",
    "cybersecurity": "cybersecurity",
    "cyber": "cybersecurity",
    "security": "cybersecurity",
    "sec": "cybersecurity",
    "education": "education",
    "edu": "education",
    "edtech": "education",
    "learn": "education",
    "cloud": "cloud",
    "devops": "cloud",
    "saas": "cloud",
    "infra": "cloud",
}


class Settings(BaseSettings):
    """Runtime settings (env-overridable)."""

    model_config = SettingsConfigDict(
        env_prefix="BRANDFORGE_",
        env_file=".env",
        extra="ignore",
    )

    min_length: int = Field(default=5, ge=3, le=12)
    max_length: int = Field(default=10, ge=4, le=20)
    target_count: int = Field(default=100_000, ge=100, le=500_000)
    top_n: int = Field(default=20, ge=1, le=100)
    concurrency: int = Field(default=20, ge=1, le=100)
    request_timeout: float = Field(default=8.0, ge=1.0, le=60.0)
    github_token: str | None = None
    check_trademark: bool = True
    generate_logos: bool = True
    user_agent: str = "BrandForge/1.0 (+https://github.com/BartuDonmez0/BrandForge)"


def get_settings() -> Settings:
    return Settings()


def resolve_category(name: str | None) -> str | None:
    if not name:
        return None
    key = name.strip().lower().replace(" ", "-")
    return CATEGORY_ALIASES.get(key, key if key in CATEGORY_PREFIXES else None)
